"""empty message

Revision ID: bab09415f533
Revises: 4cb9d952a535
Create Date: 2018-06-07 15:24:18.193460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab09415f533'
down_revision = '4cb9d952a535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_1', sa.String(200), nullable=True))
    op.add_column('t_user', sa.Column('photo_2', sa.String(200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_2')
    op.drop_column('t_user', 'photo_1')
    # ### end Alembic commands ###
